In [4]:
# 라이브러리 로드 
import pandas as pd

In [5]:
# 1차원 데이터 : 스리즈 생성 
# 데이터는 1차원 배열 
# 인덱스는 기본값 

value = [100, 200, 300, 400]

pd_series1 = pd.Series(value)


In [7]:
pd_series1

0    100
1    200
2    300
3    400
dtype: int64

In [8]:
print(pd_series1)

0    100
1    200
2    300
3    400
dtype: int64


In [9]:
# index의 값을 지정하여 Series 생성 
value = [5000, 6000, 6500, 6500]
ser_index = ['아메리카노','카페라테', '카페모카', '카푸치노']

pd_series2 = pd.Series(value, index = ser_index)

In [10]:
print(pd_series2)

아메리카노    5000
카페라테     6000
카페모카     6500
카푸치노     6500
dtype: int64


In [11]:
# Series라는 Class에는 적어도 2개의 변수가 존재 
# value , index 라는 변수가 존재 

print('Seires의 value 값은' , pd_series2.values)
print('Series의 index 값은 index', pd_series2.index)

Seires의 value 값은 [5000 6000 6500 6500]
Series의 index 값은 index Index(['아메리카노', '카페라테', '카페모카', '카푸치노'], dtype='object')


In [12]:
print(type(pd_series2.values))

<class 'numpy.ndarray'>


In [13]:
# 2차원 데이터 형태 : DataFrame 
value = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
df = pd.DataFrame(value)

In [14]:
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [15]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [17]:
value = [
    [1,2,3], 
    [4,5,6],
    [7,8,9]
]

_index = ['a','b','c']
_col = ['A','B','C']

df2 = pd.DataFrame(value, index=_index, columns= _col)



In [18]:
df2

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [19]:
#DataFrame 이라는 Class에서는 적어도 3개의 변수가 존재 
print(df2.values)
print(df2.index)
print(df2.columns)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Index(['a', 'b', 'c'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')


In [20]:
df2.columns = ['가','나','다']

In [21]:
df2

가  나  다
a  1  2  3
b  4  5  6
c  7  8  9

In [22]:
# 딕셔너리 데이터 형태 : 사전형 데이터 
# 리스트 데이터에서 index(위치)대신에 key값을 사용하는 형태 

dic_1 = {
    "name" : 'kim' , 
    "age" : 20 , 
    'phone' : "01012345678"
}

print(dic_1)
    


{'name': 'kim', 'age': 20, 'phone': '01012345678'}


In [23]:
print(dic_1['name'])

kim


In [30]:
dic_1['name'] = ['kim','park']

In [31]:
dic_1

{'name': ['kim', 'park'],
 'age': 20,
 'phone': '01012345678',
 'address': 'Seoul'}

In [32]:
dic_1['name'] = ['park']

In [33]:
dic_1

{'name': ['park'], 'age': 20, 'phone': '01012345678', 'address': 'Seoul'}

In [34]:
# 새로운 키 : 밸류 추가 
dic_1 ['address'] = 'Seoul'

In [35]:
dic_1

{'name': ['park'], 'age': 20, 'phone': '01012345678', 'address': 'Seoul'}

In [36]:
data = [
    {
        'id' : 'test',
        'password' : '1234'
    }, 
    {
        'id': 'test2',
        'password' : '0000'
    
    }
]

In [40]:
print(data [0]['id'] )

test


In [41]:
df3 = pd.DataFrame(data)

In [42]:
df3

id password
0   test     1234
1  test2     0000